/**
 * src/lib/seed/seedReviews.ts
 * 18 authentic student, athlete, and faculty reviews across all 11 catalog products.
 * Includes 1 hidden/pending moderation test review.
 */

import type { Review } from "@/types/review";

export const SEED_REVIEWS: Review[] = [
  // rs-hoodie-01: Sideline Hoodie
  {
    id: "rev-hoodie-01",
    productId: "rs-hoodie-01",
    authorName: "Elena Rostova",
    author: "Elena Rostova",
    authorGrade: "Senior · Class of '26",
    gradeLevel: "Senior",
    isVerifiedStudent: true,
    verifiedStudent: true,
    rating: 5,
    title: "Best hoodie for Friday Night football games",
    comment:
      "The double-lined hood and heavyweight fleece are incredible. Wore this to all the chilly playoff games at Gupton Stadium and stayed warm all night. The gold embroidery doesn't fray in the wash either!",
    recommend: true,
    helpfulCount: 28,
    createdAt: "2026-08-28T14:22:00Z",
    status: "approved",
  },
  {
    id: "rev-hoodie-02",
    productId: "rs-hoodie-01",
    authorName: "Marcus Chen",
    author: "Marcus Chen",
    authorGrade: "Junior",
    gradeLevel: "Junior",
    isVerifiedStudent: true,
    verifiedStudent: true,
    rating: 5,
    title: "True to size, super soft inside",
    comment:
      "I'm 6'1 and size Large fits perfectly with room for a t-shirt underneath. The maroon color matches our school fight song uniforms exactly.",
    recommend: true,
    helpfulCount: 14,
    createdAt: "2026-08-30T10:15:00Z",
    status: "approved",
  },
  {
    id: "rev-hoodie-03",
    productId: "rs-hoodie-01",
    authorName: "Taylor Brooks",
    author: "Taylor Brooks",
    authorGrade: "Sophomore",
    gradeLevel: "Sophomore",
    isVerifiedStudent: true,
    verifiedStudent: true,
    rating: 4,
    title: "Great quality, slightly snug wrists",
    comment:
      "Love the heavyweight feel! The wrist cuffs are slightly snug when pushed up on forearms, but stretches comfortably after a few days.",
    recommend: true,
    helpfulCount: 6,
    createdAt: "2026-09-01T08:45:00Z",
    status: "approved",
  },

  // rs-jacket-02: Varsity Letterman
  {
    id: "rev-jacket-01",
    productId: "rs-jacket-02",
    authorName: "Jordan Hayes",
    author: "Jordan Hayes",
    authorGrade: "Senior · Band Captain",
    gradeLevel: "Senior",
    isVerifiedStudent: true,
    verifiedStudent: true,
    rating: 5,
    title: "Heritage heirloom quality",
    comment:
      "The chenille R crest and melton wool are top-notch. Worth every penny for senior year memories. Looks amazing with jeans or over a game jersey.",
    recommend: true,
    helpfulCount: 32,
    createdAt: "2026-08-25T18:30:00Z",
    status: "approved",
  },
  {
    id: "rev-jacket-02",
    productId: "rs-jacket-02",
    authorName: "Coach Miller",
    author: "Coach Miller",
    authorGrade: "Faculty / Staff",
    gradeLevel: "Faculty / Staff",
    isVerifiedStudent: true,
    verifiedStudent: true,
    rating: 5,
    title: "Outstanding craftsmanship for our Raiders",
    comment:
      "Snap closures are heavy-duty and the leather-feel sleeves hold up great in Texas winter weather. Standard-issue Rouse pride.",
    recommend: true,
    helpfulCount: 19,
    createdAt: "2026-08-27T12:00:00Z",
    status: "approved",
  },

  // rs-cap-03: Raider Cap
  {
    id: "rev-cap-01",
    productId: "rs-cap-03",
    authorName: "Aiden Patel",
    author: "Aiden Patel",
    authorGrade: "Junior",
    gradeLevel: "Junior",
    isVerifiedStudent: true,
    verifiedStudent: true,
    rating: 5,
    title: "Structured fit that keeps its shape",
    comment:
      "The flex-stretch band fits comfortably without squeezing your temples. The raised gold embroidery looks sharp under bright stadium lights.",
    recommend: true,
    helpfulCount: 11,
    createdAt: "2026-08-29T16:10:00Z",
    status: "approved",
  },
  {
    id: "rev-cap-02",
    productId: "rs-cap-03",
    authorName: "Samira Vance",
    author: "Samira Vance",
    authorGrade: "Freshman",
    gradeLevel: "Freshman",
    isVerifiedStudent: true,
    verifiedStudent: true,
    rating: 4,
    title: "Clean embroidery, easy to adjust",
    comment:
      "Breathable eyelets keep you cool during afternoon pep rallies. Fits great even with thick curly hair.",
    recommend: true,
    helpfulCount: 5,
    createdAt: "2026-08-31T14:10:00Z",
    status: "approved",
  },

  // rs-bomber-06: Stadium Windbreaker
  {
    id: "rev-bomber-01",
    productId: "rs-bomber-06",
    authorName: "Sienna Rodriguez",
    author: "Sienna Rodriguez",
    authorGrade: "Senior · Track & Field",
    gradeLevel: "Senior",
    isVerifiedStudent: true,
    verifiedStudent: true,
    rating: 5,
    title: "Lightweight and rain-ready",
    comment:
      "Keeps the autumn rain off during track practice. Mesh lining is breathable so you don't overheat during 5th period.",
    recommend: true,
    helpfulCount: 9,
    createdAt: "2026-08-31T09:20:00Z",
    status: "approved",
  },

  // rs-sneaker-11: Raider Court Low
  {
    id: "rev-sneaker-01",
    productId: "rs-sneaker-11",
    authorName: "Devon Washington",
    author: "Devon Washington",
    authorGrade: "Junior",
    gradeLevel: "Junior",
    isVerifiedStudent: true,
    verifiedStudent: true,
    rating: 5,
    title: "Cleanest campus kicks yet",
    comment:
      "Gold heel accents give it a premium designer look. Cushioning is great for walking across the entire campus from the arts wing to the gym.",
    recommend: true,
    helpfulCount: 22,
    createdAt: "2026-08-26T11:40:00Z",
    status: "approved",
  },
  {
    id: "rev-sneaker-02",
    productId: "rs-sneaker-11",
    authorName: "Kayla Martinez",
    author: "Kayla Martinez",
    authorGrade: "Senior",
    gradeLevel: "Senior",
    isVerifiedStudent: true,
    verifiedStudent: true,
    rating: 4,
    title: "Great arch support, order true to size",
    comment:
      "Wore these all through Spirit Week. The rubber outsole grips slick cafeteria floors nicely. Looks great with ankle socks.",
    recommend: true,
    helpfulCount: 13,
    createdAt: "2026-08-29T17:25:00Z",
    status: "approved",
  },

  // rs-notebook-04: Everyday Notebook
  {
    id: "rev-notebook-01",
    productId: "rs-notebook-04",
    authorName: "Chloe Bennett",
    author: "Chloe Bennett",
    authorGrade: "Sophomore",
    gradeLevel: "Sophomore",
    isVerifiedStudent: true,
    verifiedStudent: true,
    rating: 5,
    title: "Fountain & gel pen approved! No bleed-through",
    comment:
      "Thick, high quality pages. The ribbon placeholder and gold foil Rouse seal make it look like a high-end journal.",
    recommend: true,
    helpfulCount: 15,
    createdAt: "2026-08-29T14:05:00Z",
    status: "approved",
  },

  // rs-bottle-05: Raider Water Bottle
  {
    id: "rev-bottle-01",
    productId: "rs-bottle-05",
    authorName: "Liam Garcia",
    author: "Liam Garcia",
    authorGrade: "Freshman",
    gradeLevel: "Freshman",
    isVerifiedStudent: true,
    verifiedStudent: true,
    rating: 5,
    title: "Ice stays frozen all school day",
    comment:
      "Filled with ice at 7:30 AM before first bell and it still had ice cubes after 7th period athletics. Fits in backpack side pockets easily.",
    recommend: true,
    helpfulCount: 18,
    createdAt: "2026-08-28T19:15:00Z",
    status: "approved",
  },
  {
    id: "rev-bottle-02",
    productId: "rs-bottle-05",
    authorName: "Noah Kim",
    author: "Noah Kim",
    authorGrade: "Junior",
    gradeLevel: "Junior",
    isVerifiedStudent: true,
    verifiedStudent: true,
    rating: 4,
    title: "Solid stainless steel, doesn't dent",
    comment:
      "Dropped it on the stadium bleachers and barely a scratch. Lid seal is 100% leakproof in my backpack.",
    recommend: true,
    helpfulCount: 7,
    createdAt: "2026-08-30T11:20:00Z",
    status: "approved",
  },

  // rs-blanket-07: Friday Night Blanket
  {
    id: "rev-blanket-01",
    productId: "rs-blanket-07",
    authorName: "Maya Lindqvist",
    author: "Maya Lindqvist",
    authorGrade: "Senior · Rouse Royals",
    gradeLevel: "Senior",
    isVerifiedStudent: true,
    verifiedStudent: true,
    rating: 5,
    title: "Sherpa lining is unbelievably soft",
    comment:
      "Huge 50x60 size covers two people easily on the metal bleachers. Everyone asks where we bought it during halftime!",
    recommend: true,
    helpfulCount: 21,
    createdAt: "2026-08-24T20:30:00Z",
    status: "approved",
  },

  // rs-pen-08: Precision Gel Pens · 3pk
  {
    id: "rev-pen-01",
    productId: "rs-pen-08",
    authorName: "Zachary Morris",
    author: "Zachary Morris",
    authorGrade: "Junior",
    gradeLevel: "Junior",
    isVerifiedStudent: true,
    verifiedStudent: true,
    rating: 5,
    title: "Ultra smooth 0.5mm tip",
    comment:
      "Zero smearing during rapid note taking in AP History. The matte barrel grip feels comfortable during long exam sessions.",
    recommend: true,
    helpfulCount: 8,
    createdAt: "2026-08-30T15:50:00Z",
    status: "approved",
  },

  // rs-coldbrew-09: Nitro Cold Brew
  {
    id: "rev-coldbrew-01",
    productId: "rs-coldbrew-09",
    authorName: "Alex Rivera",
    author: "Alex Rivera",
    authorGrade: "Senior",
    gradeLevel: "Senior",
    isVerifiedStudent: true,
    verifiedStudent: true,
    rating: 5,
    title: "Essential for 8 AM advisory",
    comment:
      "Smooth, velvety cold brew with no bitterness. The kiosk pickup between bells is super fast.",
    recommend: true,
    helpfulCount: 12,
    createdAt: "2026-09-01T07:55:00Z",
    status: "approved",
  },

  // rs-protein-10: Chocolate Almond Bar
  {
    id: "rev-protein-01",
    productId: "rs-protein-10",
    authorName: "Brooke Simmons",
    author: "Brooke Simmons",
    authorGrade: "Sophomore",
    gradeLevel: "Sophomore",
    isVerifiedStudent: true,
    verifiedStudent: true,
    rating: 5,
    title: "Delicious post-practice snack",
    comment:
      "Real roasted almonds and rich dark chocolate. Not chalky like typical grocery protein bars. 10/10!",
    recommend: true,
    helpfulCount: 7,
    createdAt: "2026-08-31T16:45:00Z",
    status: "approved",
  },

  // Sample Moderation Item (Hidden for admin testing)
  {
    id: "rev-hoodie-moderation-test",
    productId: "rs-hoodie-01",
    authorName: "Anonymous Raider",
    author: "Anonymous Raider",
    authorGrade: "Freshman",
    gradeLevel: "Freshman",
    isVerifiedStudent: false,
    verifiedStudent: false,
    rating: 3,
    title: "Restock needed in Small size",
    comment:
      "Loved the design but waited two weeks for size S to appear. Please stock more at the cafeteria kiosk.",
    recommend: false,
    helpfulCount: 1,
    createdAt: "2026-08-20T12:00:00Z",
    status: "hidden",
  },
];
